/* Generated by Edge Impulse
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

#include <stdint.h>
#include "model_metadata.h"

#include "tflite-model/tflite_learn_66_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"

const char* ei_classifier_inferencing_categories[] = { "DOWN", "LEFT", "RIGHT", "UP" };

uint8_t ei_dsp_config_7_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_7_axes_size = 2;
ei_dsp_config_raw_t ei_dsp_config_7 = {
    7, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    10.0f // float scale-axes
};


uint8_t ei_dsp_config_93_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_93_axes_size = 2;
ei_dsp_config_flatten_t ei_dsp_config_93 = {
    93, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    1.0f, // float scale-axes
    false, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    false, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true // boolean kurtosis
};


uint8_t ei_dsp_config_103_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_103_axes_size = 2;
ei_dsp_config_swipe_features_extraction_t ei_dsp_config_103 = {
    103, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    1.0f // float scale-axes
};

int extract_swipe_features_extraction_features(signal_t *signal, matrix_t *output_matrix, void *config_ptr, const float frequency);

const size_t ei_dsp_blocks_size = 3;
ei_model_dsp_t ei_dsp_blocks[ei_dsp_blocks_size] = {
    { // DSP block 7
        12,
        &extract_raw_features,
        (void*)&ei_dsp_config_7,
        ei_dsp_config_7_axes,
        ei_dsp_config_7_axes_size
    },
    { // DSP block 93
        10,
        &extract_flatten_features,
        (void*)&ei_dsp_config_93,
        ei_dsp_config_93_axes,
        ei_dsp_config_93_axes_size
    },
    { // DSP block 103
        2,
        &extract_swipe_features_extraction_features,
        (void*)&ei_dsp_config_103,
        ei_dsp_config_103_axes,
        ei_dsp_config_103_axes_size
    }
};
const ei_config_tflite_eon_graph_t ei_config_tflite_graph_66 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_66_init,
    .model_invoke = &tflite_learn_66_invoke,
    .model_reset = &tflite_learn_66_reset,
    .model_input = &tflite_learn_66_input,
    .model_output = &tflite_learn_66_output,
};

const ei_learning_block_config_tflite_graph_t ei_learning_block_config_66 = {
    .implementation_version = 1,
    .block_id = 66,
    .object_detection = 0,
    .object_detection_last_layer = EI_CLASSIFIER_LAST_LAYER_UNKNOWN,
    .output_data_tensor = 0,
    .output_labels_tensor = 1,
    .output_score_tensor = 2,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_tflite_graph_66
};

const size_t ei_learning_blocks_size = 1;
const ei_learning_block_t ei_learning_blocks[ei_learning_blocks_size] = {
    {
        &run_nn_inference,
        (void*)&ei_learning_block_config_66,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
    },
};

const ei_model_performance_calibration_t ei_calibration = {
    1, /* integer version number */
    false, /* has configured performance calibration */
    (int32_t)(EI_CLASSIFIER_RAW_SAMPLE_COUNT / ((EI_CLASSIFIER_FREQUENCY > 0) ? EI_CLASSIFIER_FREQUENCY : 1)) * 1000, /* Model window */
    0.8f, /* Default threshold */
    (int32_t)(EI_CLASSIFIER_RAW_SAMPLE_COUNT / ((EI_CLASSIFIER_FREQUENCY > 0) ? EI_CLASSIFIER_FREQUENCY : 1)) * 500, /* Half of model window */
    0   /* Don't use flags */
};

const ei_impulse_t impulse_269854_1 = {
    .project_id = 269854,
    .project_owner = "Jordan Karyanto",
    .project_name = "SWIPE_Detection",
    .deploy_version = 1,

    .nn_input_frame_size = 24,
    .raw_sample_count = 6,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 6 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 10,
    .frequency = 100,
    .dsp_blocks_size = ei_dsp_blocks_size,
    .dsp_blocks = ei_dsp_blocks,
    
    .object_detection = 0,
    .object_detection_count = 0,
    .object_detection_threshold = 0,
    .object_detection_last_layer = EI_CLASSIFIER_LAST_LAYER_UNKNOWN,
    .fomo_output_size = 0,
    
    .tflite_output_features_count = 4,
    .learning_blocks_size = ei_learning_blocks_size,
    .learning_blocks = ei_learning_blocks,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "X + Y",
    .slice_size = (6/4),
    .slices_per_model_window = 4,

    .has_anomaly = 0,
    .label_count = 4,
    .calibration = ei_calibration,
    .categories = ei_classifier_inferencing_categories
};

const ei_impulse_t ei_default_impulse = impulse_269854_1;

#endif // _EI_CLASSIFIER_MODEL_METADATA_H_
